In [262]:
import numpy as np
import matplotlib as mpl
%load_ext autoreload
%autoreload 2
np.set_printoptions(linewidth=120, precision=4)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [286]:
npts = 9
x = np.linspace(1.0, 10.0, npts)
# x = np.geomspace(2.0, 10.0, npts)
print('x', x)

x [ 1.     2.125  3.25   4.375  5.5    6.625  7.75   8.875 10.   ]


In [287]:
XX = np.empty((npts, npts))
# XX = np.array([x1+x2 for x1 in x for x2 in x])
for i, x1 in enumerate(x):
    for j, x2 in enumerate(x):
        XX[i,j] = x1 + x2
print('SOMA')
print(XX)

SOMA
[[ 2.     3.125  4.25   5.375  6.5    7.625  8.75   9.875 11.   ]
 [ 3.125  4.25   5.375  6.5    7.625  8.75   9.875 11.    12.125]
 [ 4.25   5.375  6.5    7.625  8.75   9.875 11.    12.125 13.25 ]
 [ 5.375  6.5    7.625  8.75   9.875 11.    12.125 13.25  14.375]
 [ 6.5    7.625  8.75   9.875 11.    12.125 13.25  14.375 15.5  ]
 [ 7.625  8.75   9.875 11.    12.125 13.25  14.375 15.5   16.625]
 [ 8.75   9.875 11.    12.125 13.25  14.375 15.5   16.625 17.75 ]
 [ 9.875 11.    12.125 13.25  14.375 15.5   16.625 17.75  18.875]
 [11.    12.125 13.25  14.375 15.5   16.625 17.75  18.875 20.   ]]


In [288]:
i_ref = 5
x_ref = x[i_ref]
x_ref

6.625

In [289]:
XX - x_ref

array([[-4.625, -3.5  , -2.375, -1.25 , -0.125,  1.   ,  2.125,  3.25 ,  4.375],
       [-3.5  , -2.375, -1.25 , -0.125,  1.   ,  2.125,  3.25 ,  4.375,  5.5  ],
       [-2.375, -1.25 , -0.125,  1.   ,  2.125,  3.25 ,  4.375,  5.5  ,  6.625],
       [-1.25 , -0.125,  1.   ,  2.125,  3.25 ,  4.375,  5.5  ,  6.625,  7.75 ],
       [-0.125,  1.   ,  2.125,  3.25 ,  4.375,  5.5  ,  6.625,  7.75 ,  8.875],
       [ 1.   ,  2.125,  3.25 ,  4.375,  5.5  ,  6.625,  7.75 ,  8.875, 10.   ],
       [ 2.125,  3.25 ,  4.375,  5.5  ,  6.625,  7.75 ,  8.875, 10.   , 11.125],
       [ 3.25 ,  4.375,  5.5  ,  6.625,  7.75 ,  8.875, 10.   , 11.125, 12.25 ],
       [ 4.375,  5.5  ,  6.625,  7.75 ,  8.875, 10.   , 11.125, 12.25 , 13.375]])

In [290]:
XX - x[i_ref + 1]

array([[-5.75 , -4.625, -3.5  , -2.375, -1.25 , -0.125,  1.   ,  2.125,  3.25 ],
       [-4.625, -3.5  , -2.375, -1.25 , -0.125,  1.   ,  2.125,  3.25 ,  4.375],
       [-3.5  , -2.375, -1.25 , -0.125,  1.   ,  2.125,  3.25 ,  4.375,  5.5  ],
       [-2.375, -1.25 , -0.125,  1.   ,  2.125,  3.25 ,  4.375,  5.5  ,  6.625],
       [-1.25 , -0.125,  1.   ,  2.125,  3.25 ,  4.375,  5.5  ,  6.625,  7.75 ],
       [-0.125,  1.   ,  2.125,  3.25 ,  4.375,  5.5  ,  6.625,  7.75 ,  8.875],
       [ 1.   ,  2.125,  3.25 ,  4.375,  5.5  ,  6.625,  7.75 ,  8.875, 10.   ],
       [ 2.125,  3.25 ,  4.375,  5.5  ,  6.625,  7.75 ,  8.875, 10.   , 11.125],
       [ 3.25 ,  4.375,  5.5  ,  6.625,  7.75 ,  8.875, 10.   , 11.125, 12.25 ]])

In [291]:
XX - x[i_ref - 1]

array([[-3.5  , -2.375, -1.25 , -0.125,  1.   ,  2.125,  3.25 ,  4.375,  5.5  ],
       [-2.375, -1.25 , -0.125,  1.   ,  2.125,  3.25 ,  4.375,  5.5  ,  6.625],
       [-1.25 , -0.125,  1.   ,  2.125,  3.25 ,  4.375,  5.5  ,  6.625,  7.75 ],
       [-0.125,  1.   ,  2.125,  3.25 ,  4.375,  5.5  ,  6.625,  7.75 ,  8.875],
       [ 1.   ,  2.125,  3.25 ,  4.375,  5.5  ,  6.625,  7.75 ,  8.875, 10.   ],
       [ 2.125,  3.25 ,  4.375,  5.5  ,  6.625,  7.75 ,  8.875, 10.   , 11.125],
       [ 3.25 ,  4.375,  5.5  ,  6.625,  7.75 ,  8.875, 10.   , 11.125, 12.25 ],
       [ 4.375,  5.5  ,  6.625,  7.75 ,  8.875, 10.   , 11.125, 12.25 , 13.375],
       [ 5.5  ,  6.625,  7.75 ,  8.875, 10.   , 11.125, 12.25 , 13.375, 14.5  ]])

In [292]:
(x[i_ref+1] - XX[0, 5]) / (x[i_ref+1] - x[i_ref])

0.1111111111111111

In [294]:
# i_ref = 5
# knovo = 0
# for j in range(0, i_ref + 1):
#     for k in range(0, j + 1):    
#         nu = x[j] + x[k]
#         if nu > x[i_ref - 1]:
#             if k < j + 1:
#                 knovo = 0; print('less', knovo)
#             else:
#                 knovo = j + 1; print('uppe', knovo)

In [359]:
x = np.geomspace(1.0, 1e5, 1001)
i_ref = 200
[np.searchsorted(x[0:j_ref], x[i_ref] - x[j_ref]) for j_ref in range(1, i_ref-1)]

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 139,
 138,
 137,
 136,
 135,
 134,
 132,
 131,
 130,
 129,
 127,
 126,
 125,
 123,
 122,
 120,
 119,
 117,
 116,
 114,
 112,
 110,
 109,
 107,
 105,
 103,
 100,
 98,
 96,
 94,
 91,
 89,
 86,
 83,
 80,
 77,
 74,
 70,
 67,
 63,
 59,
 55,
 50,
 46,
 41,
 35,
 29,
 23,
 

In [358]:
x

array([1.0000e+00, 1.0116e+00, 1.0233e+00, 1.0351e+00, 1.0471e+00, 1.0593e+00, 1.0715e+00, 1.0839e+00, 1.0965e+00,
       1.1092e+00, 1.1220e+00, 1.1350e+00, 1.1482e+00, 1.1614e+00, 1.1749e+00, 1.1885e+00, 1.2023e+00, 1.2162e+00,
       1.2303e+00, 1.2445e+00, 1.2589e+00, 1.2735e+00, 1.2882e+00, 1.3032e+00, 1.3183e+00, 1.3335e+00, 1.3490e+00,
       1.3646e+00, 1.3804e+00, 1.3964e+00, 1.4125e+00, 1.4289e+00, 1.4454e+00, 1.4622e+00, 1.4791e+00, 1.4962e+00,
       1.5136e+00, 1.5311e+00, 1.5488e+00, 1.5668e+00, 1.5849e+00, 1.6032e+00, 1.6218e+00, 1.6406e+00, 1.6596e+00,
       1.6788e+00, 1.6982e+00, 1.7179e+00, 1.7378e+00, 1.7579e+00, 1.7783e+00, 1.7989e+00, 1.8197e+00, 1.8408e+00,
       1.8621e+00, 1.8836e+00, 1.9055e+00, 1.9275e+00, 1.9498e+00, 1.9724e+00, 1.9953e+00, 2.0184e+00, 2.0417e+00,
       2.0654e+00, 2.0893e+00, 2.1135e+00, 2.1380e+00, 2.1627e+00, 2.1878e+00, 2.2131e+00, 2.2387e+00, 2.2646e+00,
       2.2909e+00, 2.3174e+00, 2.3442e+00, 2.3714e+00, 2.3988e+00, 2.4266e+00, 2

In [355]:
x[i_ref]

1.4125375446227544

In [357]:
x[i_ref-1]

1.3963683610559376

# Symbolic

In [270]:
import sympy
x = sympy.symbols('x0:9')
XX = []
# for i, x1 in enumerate(x):
#     XXaux = [ [] for _ in range(npts)]
#     for j, x2 in enumerate(x):
#         XXaux[j] = x1 + x2
#     XX.append(XXaux)
XX = [ [x1 + x2 for x1 in x] for x2 in x]
for i, el in enumerate(XX):
    print(el)

[2*x0, x0 + x1, x0 + x2, x0 + x3, x0 + x4, x0 + x5, x0 + x6, x0 + x7, x0 + x8]
[x0 + x1, 2*x1, x1 + x2, x1 + x3, x1 + x4, x1 + x5, x1 + x6, x1 + x7, x1 + x8]
[x0 + x2, x1 + x2, 2*x2, x2 + x3, x2 + x4, x2 + x5, x2 + x6, x2 + x7, x2 + x8]
[x0 + x3, x1 + x3, x2 + x3, 2*x3, x3 + x4, x3 + x5, x3 + x6, x3 + x7, x3 + x8]
[x0 + x4, x1 + x4, x2 + x4, x3 + x4, 2*x4, x4 + x5, x4 + x6, x4 + x7, x4 + x8]
[x0 + x5, x1 + x5, x2 + x5, x3 + x5, x4 + x5, 2*x5, x5 + x6, x5 + x7, x5 + x8]
[x0 + x6, x1 + x6, x2 + x6, x3 + x6, x4 + x6, x5 + x6, 2*x6, x6 + x7, x6 + x8]
[x0 + x7, x1 + x7, x2 + x7, x3 + x7, x4 + x7, x5 + x7, x6 + x7, 2*x7, x7 + x8]
[x0 + x8, x1 + x8, x2 + x8, x3 + x8, x4 + x8, x5 + x8, x6 + x8, x7 + x8, 2*x8]


In [271]:
i_ref = 5
x_ref = x[i_ref]
x_ref

x5

In [272]:
XXless_i_ref = [ [ x1+x2 - x_ref for x1 in x] for x2 in x]
for i, el in enumerate(XXless_i_ref):
    print(el)

[2*x0 - x5, x0 + x1 - x5, x0 + x2 - x5, x0 + x3 - x5, x0 + x4 - x5, x0, x0 - x5 + x6, x0 - x5 + x7, x0 - x5 + x8]
[x0 + x1 - x5, 2*x1 - x5, x1 + x2 - x5, x1 + x3 - x5, x1 + x4 - x5, x1, x1 - x5 + x6, x1 - x5 + x7, x1 - x5 + x8]
[x0 + x2 - x5, x1 + x2 - x5, 2*x2 - x5, x2 + x3 - x5, x2 + x4 - x5, x2, x2 - x5 + x6, x2 - x5 + x7, x2 - x5 + x8]
[x0 + x3 - x5, x1 + x3 - x5, x2 + x3 - x5, 2*x3 - x5, x3 + x4 - x5, x3, x3 - x5 + x6, x3 - x5 + x7, x3 - x5 + x8]
[x0 + x4 - x5, x1 + x4 - x5, x2 + x4 - x5, x3 + x4 - x5, 2*x4 - x5, x4, x4 - x5 + x6, x4 - x5 + x7, x4 - x5 + x8]
[x0, x1, x2, x3, x4, x5, x6, x7, x8]
[x0 - x5 + x6, x1 - x5 + x6, x2 - x5 + x6, x3 - x5 + x6, x4 - x5 + x6, x6, -x5 + 2*x6, -x5 + x6 + x7, -x5 + x6 + x8]
[x0 - x5 + x7, x1 - x5 + x7, x2 - x5 + x7, x3 - x5 + x7, x4 - x5 + x7, x7, -x5 + x6 + x7, -x5 + 2*x7, -x5 + x7 + x8]
[x0 - x5 + x8, x1 - x5 + x8, x2 - x5 + x8, x3 - x5 + x8, x4 - x5 + x8, x8, -x5 + x6 + x8, -x5 + x7 + x8, -x5 + 2*x8]
